### PR TITLE
Add a Postgres service

### PR DESCRIPTION
**Pull request by seanh**
<del>Depends on https://github.com/hypothesis/cookiecutters/pull/97.</del>

This is just the result of setting `"postgres"` to `"yes"` in `cookiecutter.json` and also setting `"__postgres_port"` and then running `make template`.

Testing:

- [x] `make services` works
- [x] `make sql` works
- [x] `make sure` works
- [x] CI passes

### CODE REVIEW

**Comment by jon-betts** [comment]
I wonder if we might be better off with things as they are? I think SQLite is sufficient for the testing in this project and means one less moving part. As `sqlite3` is a part of the standard library in Python, this isn't a case of swapping components but adding them.

The code here is written in a way which shouldn't cause surprise to a developer as it uses the same structure and layout as any other project. The only difference is the database DNS points to an in memory SQLite DB vs. Postgres.

Kind of a YAGNI situation?

**Comment by seanh** [comment]
> I wonder if we might be better off with things as they are? I think SQLite is sufficient for the testing in this project and means one less moving part. As `sqlite3` is a part of the standard library in Python, this isn't a case of swapping components but adding them.
> 
> The code here is written in a way which shouldn't cause surprise to a developer as it uses the same structure and layout as any other project. The only difference is the database DNS points to an in memory SQLite DB vs. Postgres.
> 
> Kind of a YAGNI situation?

Up to you guys.

I think my take is that getting Postgres support in dev and on CI is basically free: you just set `"db"` to `"yes"` in `cookiecutter.json` and then run `make template`. This is making use of the same cookiecutter Postgres feature that will be used by our other Postgres-using projects once the cookiecutter gets applied to those projects. Currently those projects do already use Postgres in this same exact way, even though they don't actually have the cookiecutter applied yet. So there's no extra cost to maintaining this Postgres support for the data-tasks project: it's the same Postgres support as we're already maintaining for other projects. This way you have the same DB in dev and on CI as in production.

**Review by marcospri — CHANGES_REQUESTED** [review]
Is `docker compose` correct? 

In my machine I need to do `docker-compose` maybe that's a new version of docker, should I upgrade to that? I the same version avaible in mac etc?

I reckon that together with this we should switch from sqlite to postgres, something along this lines:


```diff
diff --git a/.cookiecutter/includes/setuptools/install_requires b/.cookiecutter/includes/setuptools/install_requires
index 6a2b317..4b62335 100644
--- a/.cookiecutter/includes/setuptools/install_requires
+++ b/.cookiecutter/includes/setuptools/install_requires
@@ -1,5 +1,6 @@
 importlib_resources
 jinja2
 SQLAlchemy
+psycopg2
 sqlparse
 tabulate
diff --git a/setup.cfg b/setup.cfg
index 66ba9d3..5794a12 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -22,6 +22,7 @@ install_requires =
     importlib_resources
     jinja2
     SQLAlchemy
+    psycopg2
     sqlparse
     tabulate
 
diff --git a/tests/conftest.py b/tests/conftest.py
index cc6ddc7..74a047f 100644
--- a/tests/conftest.py
+++ b/tests/conftest.py
@@ -3,7 +3,7 @@ import os
 import pytest
 import sqlalchemy
 
-TEST_SETTINGS = {"database_url": os.environ.get("TEST_DATABASE_URL", "sqlite://")}
+TEST_SETTINGS = {"database_url": os.environ.get("TEST_DATABASE_URL", "postgresql://postgres@localhost:5439/data_tasks_test")}
 
 
 @pytest.fixture(scope="session")
```

**Comment by seanh** [comment]
> Is `docker compose` correct?
> 
> In my machine I need to do `docker-compose` maybe that's a new version of docker, should I upgrade to that? I the same version avaible in mac etc?

Yeah, you need [Docker Desktop](https://www.docker.com/products/docker-desktop/) >= [4.12.0](https://docs.docker.com/desktop/release-notes/#4120). They've reimplemented the `docker-compose` Python package as a `docker compose` subcommand (completely rewritten in Go) that ships with Docker Desktop. It's being called [Compose V2](https://docs.docker.com/compose/compose-v2/). The old Docker Compose V1 (the `docker-compose` command that was written in Python) [is deprecated](https://www.docker.com/blog/announcing-compose-v2-general-availability/).

**Comment by seanh** [comment]
> I reckon that together with this we should switch from sqlite to postgres, something along this lines:
> 
> ```diff
> diff --git a/.cookiecutter/includes/setuptools/install_requires b/.cookiecutter/includes/setuptools/install_requires
> index 6a2b317..4b62335 100644
> --- a/.cookiecutter/includes/setuptools/install_requires
> +++ b/.cookiecutter/includes/setuptools/install_requires
> @@ -1,5 +1,6 @@
>  importlib_resources
>  jinja2
>  SQLAlchemy
> +psycopg2
>  sqlparse
>  tabulate
> diff --git a/setup.cfg b/setup.cfg
> index 66ba9d3..5794a12 100644
> --- a/setup.cfg
> +++ b/setup.cfg
> @@ -22,6 +22,7 @@ install_requires =
>      importlib_resources
>      jinja2
>      SQLAlchemy
> +    psycopg2
>      sqlparse
>      tabulate
>  
> diff --git a/tests/conftest.py b/tests/conftest.py
> index cc6ddc7..74a047f 100644
> --- a/tests/conftest.py
> +++ b/tests/conftest.py
> @@ -3,7 +3,7 @@ import os
>  import pytest
>  import sqlalchemy
>  
> -TEST_SETTINGS = {"database_url": os.environ.get("TEST_DATABASE_URL", "sqlite://")}
> +TEST_SETTINGS = {"database_url": os.environ.get("TEST_DATABASE_URL", "postgresql://postgres@localhost:5439/data_tasks_test")}
>  
>  
>  @pytest.fixture(scope="session")
> ```

This is because I just tested that `make services` and `make sql` work but didn't actually test that the Python code can connect to the DB :facepalm: :facepalm: :facepalm: We should add this to the cookiecutter: it should automatically add the `psycopg2` dependency if `db` is `yes`. I'll give it a try...

**Comment by seanh** [comment]
See https://github.com/hypothesis/cookiecutters/pull/103 and https://github.com/hypothesis/data-tasks/pull/8

**Comment by seanh** [comment]
Ok, this has been updated to add the `sqlalchemy` and `psycopg2` dependences and the `DATABASE_URL` and `TEST_DATABASE_URL` envvars and to change the tests from SQLite to Postgres.

@marcospri @jon-betts Up to you guys if you want to merge this or just stick with SQLite. Wanting to add Postgres to data-tasks inspired https://github.com/hypothesis/cookiecutters/pull/98, https://github.com/hypothesis/cookiecutters/pull/97 and https://github.com/hypothesis/cookiecutters/pull/103 which have added actually-working services and Postgres support to the cookiecutter, made services and Postgres available to packages (not just apps), upgraded to Docker Compose V2, etc. This work will be useful (in fact necessary) when we apply the cookiecutter to our services-using apps so nothing's wasted.

**Review by marcospri — APPROVED** [review]
Yeah now that this comes for "free" from the cookie cutter it makes sense to use postgres :+1:

**Pull request merged**
